Dls 6658
hmrc/soft-drinks-industry-levy-returns-frontend pull request #42
Opened 2023-01-09 09:36 UTC by JakeReid2020

2023-01-09 10:51 UTC, priyankadhiman3006 commented on app/controllers/SmallProducerDetailsController.scala
>    val spList = List(SmallProducer("ABC Ltd", "SDIL123456", (1000L, 1000L)),
now this data should come from the previous page and this hard coded values should be removed

2023-01-09 10:53 UTC, priyankadhiman3006 commented on app/controllers/SmallProducerDetailsController.scala
>        val smallProducersSummaryList: List[SummaryListRow] = SmallProducerDetailsSummary.row2(spList)
is it possible to  do this calculation one time and not again as done at line no 61?

2023-01-09 10:57 UTC, priyankadhiman3006 commented
click on Edit link, takes the user to add small producer page but the it's blank. the older details are not there. Is this the behaviour in old code

2023-01-09 11:03 UTC, priyankadhiman3006 commented on app/navigation/Navigator.scala
> +    case SmallProducerDetailsPage => userAnswers => smallProducerDetailsPageNavigation(userAnswers)
Need unit test cases for this under NavigatorSpec

2023-01-16 08:52 UTC, RaminEsfandiari commented
@JakeReid2020 we have some failing tests. Happy to investigate with you.
![image](https://user-images.githubusercontent.com/5639505/212636703-ee89a68c-75cb-4ccd-893d-39a31a28f88c.png)

2023-01-16 08:57 UTC, JakeReid2020 commented
> @JakeReid2020, Although not one of the changes on this PR, we have some failing tests. Happy to investigate with you on a spike ticket. ![image](https://user-images.githubusercontent.com/5639505/212636703-ee89a68c-75cb-4ccd-893d-39a31a28f88c.png)

@RaminEsfandiari I think this is a flakey test, run again it passes we can have a look at making them more reliable.

2023-01-16 10:14 UTC, RaminEsfandiari requested changes
Just a few minor changes otherwise it looks good I think.

2023-01-16 10:14 UTC, RaminEsfandiari commented on it/controllers/testSupport/ITCoreTestData.scala
> +    .set(AddASmallProducerPage, AddASmallProducer(Some("Super Cola Ltd"),"XZSDIL000000234",1000L, 1000L))
Best create a val for those hard coded values and reuse them instead of repeating the same hard coded values in two tests.

2023-01-16 10:14 UTC, RaminEsfandiari commented on it/controllers/RemoveSmallProducerConfirmControllerIntegrationSpec.scala
> +        val largeLire = largeLiremax - 1
Can we have these as global test values to remove duplication?

2023-01-16 10:14 UTC, RaminEsfandiari commented on it/controllers/RemoveSmallProducerConfirmControllerIntegrationSpec.scala
> +        val largeLire = largeLiremax - 1
Can we have these as global test values to remove duplication?

2023-01-16 10:14 UTC, RaminEsfandiari commented on it/controllers/RemoveSmallProducerConfirmControllerIntegrationSpec.scala
> +      val largeLire = largeLiremax - 1
Can we have these as global test values to remove duplication?

2023-01-16 10:14 UTC, RaminEsfandiari commented on app/controllers/RemoveSmallProducerConfirmController.scala
> +      //val smallProducerRef = request.userAnswers.smallProducerList.map(producer => producer.sdilRef.filter(_ == sdil))
We can remove this line.

2023-01-16 10:14 UTC, RaminEsfandiari commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.7.2","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java","-Xms100m","-Xmx100m","-classpa
We should add this file to .gitignore maybe as it is specific to the user's development IDE and one and doesn't need to tracked

2023-01-16 11:35 UTC, RaminEsfandiari approved these changes

2023-01-16 11:35 UTC, merged