DlS-6532 - Check your answers page
hmrc/soft-drinks-industry-levy-returns-frontend pull request #70
Opened 2023-03-29 13:37 UTC by RaminEsfandiari

2023-03-31 13:17 UTC, ChrisHillCap requested changes
Finishing the review. 
I understand it is still being worked on
The integration tests can be done as part of another ticket at this stage
The removing of page data upon clicking NO should probably be more generic, seperate story.

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ClaimCreditsForExportsController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
we should steer away from fire and forget calls, we want this to happen and we want to know about it  if it fails. can you please map onto the redirect

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/BroughtIntoUkFromSmallProducersController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
we should steer away from fire and forget calls, we want this to happen and we want to know about it  if it fails. can you please map onto the redirect

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/CheckYourAnswersController.scala
> +      cacheAmounts(sdilEnrolment, Amounts(totalForQuarter, balanceBroughtForward, total))
please make sure you map from a future to the result

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/CheckYourAnswersController.scala
>  class CheckYourAnswersController @Inject()(
Ive noticed almost all functions and vals don't have the type declared in this file, i believe this is a scala warning and just makes it less readable IMO

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/CheckYourAnswersController.scala
> +    val balanceAllEnabled = config.balanceAllEnabled
this is only used once, why does it need to be a val

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ClaimCreditsForLostDamagedController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
map please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ExemptionsForSmallProducersController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
map please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/OwnBrandsController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
map please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/PackagedContractPackerController.scala
> +              val answersWithLitresRemoved =
is the val meant to be called this?

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/OwnBrandsController.scala
> +              val answersWithLitresRemoved =
is the val meant to be called this?

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ReturnsController.scala
> +              returnPeriod, // TODO - I don't think this needs to be passed twice :)
can we raise a story on this referencing line of code and remove todo

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ReturnsController.scala
> +              warehouseCheck = warehouseCheck(warehouseList): Option[List[Warehouse]], //TODO CHANGE TO CHECK WAREHOUSE LIST!
can we raise a story on this if youve added the todo and remove the todo

2023-03-31 13:17 UTC, ChrisHillCap commented on app/controllers/ReturnsController.scala
> +class ReturnsController @Inject()(
this is too much to review, from the demo and what we went through it looks ok

2023-03-31 13:17 UTC, ChrisHillCap commented on app/navigation/Navigator.scala
> +
confused on this, i noticed it no longer being used in a certain place, and all these todos, these todos should be stories

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/AmountToPaySummary.scala
> +    // TODO - ask Jake why he is adding the total from small producer
story please, remove todo

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyBroughtIntoTheUKFromSmallProducersSummary.scala
> +        // TODO - are there any conditions under which this is chargeable ????? if not then we don't need lowBandCostPerLitre to be passed in
story, conversation or remove please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyBroughtIntoTheUKFromSmallProducersSummary.scala
> +        // TODO - are there any conditions under which this is chargeable ?????
post it on our  jamboard maybe?

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyCreditsForExportSummary.scala
> +        val levy = "-£" + String.format("%.2f", (answer.lowBand * lowBandCostPerLitre.toDouble))
is this dash meant to be here, and is this calculation correct?

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyCreditsForExportSummary.scala
> +        val levy = "-£" + String.format("%.2f", (answer.highBand * highBandCostPerLitre.toDouble))
again with the dash, confused why its there

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyCreditsForLostDamagedSummary.scala
>          val value = HtmlFormat.escape(levy).toString
dash again, confused :)

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/HowManyCreditsForLostDamagedSummary.scala
> +        val levy = "-£" + String.format("%.2f", (answer.highBand * highBandCostPerLitre.toDouble))
dash

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/PackAtBusinessAddressSummary.scala
> +    //  i.e addressList.size which will probably be saved in the user answers
put in a story / the story its meant to be associated with and remove please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/PackAtBusinessAddressSummary.scala
> +          value   = ValueViewModel("1").withCssClass("align-right"), //- TODO Change value to number of sites after the page is implemented
story and remove please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/SmallProducerDetailsSummary.scala
> +        //val levy = answers.smallProducerList.map(highBand => highBand.litreage._2).sum * highBandCostPerLitre.toDouble * 0
story / post it and remove please

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/SmallProducerDetailsSummary.scala
> +        /// val levy = answers.smallProducerList.map(lowBand => lowBand.litreage._1).sum * lowBandCostPerLitre.toDouble * 0
story / post it  and remove please

2023-03-31 13:17 UTC, ChrisHillCap commented on build.sbt
> +  .settings(majorVersion := 0, libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always) // libraryDependencySchemes added to get around the scoverage compile errors
is the comment adding anything

2023-03-31 13:17 UTC, ChrisHillCap commented on conf/application.conf
> +balanceAll.enabled = false
what does this affect in QA, i still don't really understand this

2023-03-31 13:17 UTC, ChrisHillCap commented on conf/messages.en
> +firstQuarter = January to March
shouldnt all / some of these messages be prefixed with "checkYourAnswers." ?

2023-03-31 13:17 UTC, ChrisHillCap commented on conf/messages.en
> +financiallineitem.returncharge = Return <br/><span class="form-hint">for {0} to {1}</span>
why have we done this, rather than use multiple messages

2023-03-31 13:17 UTC, ChrisHillCap commented on it/controllers/CheckYourAnswersControllerIntegrationSpec.scala
> +  "CheckYourAnswersController" should {
Your controller is huge, i would expect alot more tests in here. seperate subtask if you want as part of this story

2023-03-31 13:17 UTC, ChrisHillCap commented on it/controllers/ClaimCreditsForLostDamagedControllerIntegrationSpec.scala
> -      "user selected no " when {
why is this removed

2023-03-31 13:17 UTC, ChrisHillCap commented on app/viewmodels/checkAnswers/BrandsPackagedAtOwnSitesSummary.scala
> +        val value = HtmlFormat.escape(CurrencyFormatter.formatAmountOfMoneyWithPoundSign(levy)).toString
how come youve used this Currency Formatter in some places but not others? 
Search for "£" + String.format("%,.2f") and you will find others in your pr

2023-03-31 13:17 UTC, ChrisHillCap commented on app/navigation/Navigator.scala
> +    case ClaimCreditsForLostDamagedPage => userAnswers => _ => _ => _ => claimCreditsForLostDamagedPageNavigation(userAnswers)
Was this meant to change? may need a little overview of this

2023-03-31 13:17 UTC, ChrisHillCap commented on app/navigation/Navigator.scala
> +    case OwnBrandsPage => userAnswers => checkOwnBrandPageNavigation(userAnswers)
is all of this tested?

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/BroughtIntoUkFromSmallProducersController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
@ChrisHillCap Agreed. Something like the following maybe?

```
else {
     updatedAnswers.remove(HowManyBroughtIntoUkPage) match {
        case Success(updatedAnswers) =>
            sessionRepository.set(updatedAnswers)
            Redirect(navigator.nextPage(BroughtIntoUKPage, mode, updatedAnswers))
         case Failure(exception) =>
            logger.error(s"Failed to remove value \n ${exception.getMessage}")
            Redirect(routes.JourneyRecoveryController.onPageLoad())
          }
     }
```

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/BroughtIntoUkFromSmallProducersController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
Also I noticed you mention map further down the PR so maybe the following:

```
              updatedAnswers.remove(HowManyBroughtIntoUkPage).map {
                updatedAnswers =>
                  sessionRepository.set(updatedAnswers)
                  Redirect(navigator.nextPage(BroughtIntoUKPage, mode, updatedAnswers))
              }.recover {
                case e =>
                  logger.error(s"Failed to remove litres data \n ${e.getMessage}")
                  Redirect(routes.JourneyRecoveryController.onPageLoad())
              }
```

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/BroughtIntoUkFromSmallProducersController.scala
> +              sessionRepository.set(answersWithLitresRemoved)
Resolved together on the mob call.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/CheckYourAnswersController.scala
>  class CheckYourAnswersController @Inject()(
Personally I find including the types adds a bit of noise where we can use the IDE's type hints or hover function to see the type when we need to and that arguably allows people to view it they way they prefer but I think the consensus across HMRC seems to be to include the types so happy to adhere to that.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/ReturnsController.scala
> +              returnPeriod, // TODO - I don't think this needs to be passed twice :)
Added as a subtask under Returns controller ticket (DLS-6533)

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/ReturnsController.scala
> +              warehouseCheck = warehouseCheck(warehouseList): Option[List[Warehouse]], //TODO CHANGE TO CHECK WAREHOUSE LIST!
Added as a subtask under Returns controller ticket (DLS-6533)

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/navigation/Navigator.scala
> +    case ClaimCreditsForLostDamagedPage => userAnswers => _ => _ => _ => claimCreditsForLostDamagedPageNavigation(userAnswers)
Yes, this will be addressed as part of DLS-6667 (Lost or Damaged navigation). The inherited LostOrDamagedController seemed to suggest calculating the SdilReturn and then calling CYA which makes sense if we want to keep the CYA dumb. For the time being though I think it would be fair to keep the calculation in CYA and then refactor it to LostOrDamaged. Let me know what you think.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/navigation/Navigator.scala
> +    case OwnBrandsPage => userAnswers => checkOwnBrandPageNavigation(userAnswers)
They are now.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/navigation/Navigator.scala
> +
I agree. This section will also be addressed as part of DLS-6667 (Lost or Damaged navigation)

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/controllers/ReturnsController.scala
> +class ReturnsController @Inject()(
Fair point.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/AmountToPaySummary.scala
> +    // TODO - ask Jake why he is adding the total from small producer
Removed, story exists for returns controller. Will add a comment mentioning this.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/BrandsPackagedAtOwnSitesSummary.scala
> +        val value = HtmlFormat.escape(CurrencyFormatter.formatAmountOfMoneyWithPoundSign(levy)).toString
Missed a couple as part of a refactoring

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/HowManyBroughtIntoTheUKFromSmallProducersSummary.scala
> +        // TODO - are there any conditions under which this is chargeable ????? if not then we don't need lowBandCostPerLitre to be passed in
I'll have another poke around the old FE to double check and start a Slack conversation if I can't wrap my head around it.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/HowManyBroughtIntoTheUKFromSmallProducersSummary.scala
> +        // TODO - are there any conditions under which this is chargeable ?????
Done

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/HowManyCreditsForExportSummary.scala
> +        val levy = "-£" + String.format("%.2f", (answer.lowBand * lowBandCostPerLitre.toDouble))
Cleaned up with the formatter now. The result should be a negative number.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/HowManyCreditsForLostDamagedSummary.scala
>          val value = HtmlFormat.escape(levy).toString
Replaced with currency fomatter.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/PackAtBusinessAddressSummary.scala
> +    //  i.e addressList.size which will probably be saved in the user answers
Removed. Added a post it on Jamboard to create the ticket.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/PackAtBusinessAddressSummary.scala
> +          value   = ValueViewModel("1").withCssClass("align-right"), //- TODO Change value to number of sites after the page is implemented
Removed. Added a post it on Jamboard to create the ticket.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/SmallProducerDetailsSummary.scala
> +        /// val levy = answers.smallProducerList.map(lowBand => lowBand.litreage._1).sum * lowBandCostPerLitre.toDouble * 0
Post it created as part of an earlier todo removal.

2023-04-04 14:31 UTC, RaminEsfandiari commented on app/viewmodels/checkAnswers/SmallProducerDetailsSummary.scala
> +        //val levy = answers.smallProducerList.map(highBand => highBand.litreage._2).sum * highBandCostPerLitre.toDouble * 0
Post it created as part of an earlier todo removal.

2023-04-04 14:31 UTC, RaminEsfandiari commented on build.sbt
> +  .settings(majorVersion := 0, libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always) // libraryDependencySchemes added to get around the scoverage compile errors
Well, this is in case anyone wonders why this was added but happy to remove it as I am not a big fan of comments as they could be misrepresentative of the code they are trying to add context to if people make changes to code and ignore the comment. It kinda made sense to leave something here given it is out of the boundaries of normal config and may raise a few questions for the person looking at it as to why this dependency was added. Happy to remove it if you think it's unnecessary.

2023-04-04 14:31 UTC, RaminEsfandiari commented on conf/application.conf
> +balanceAll.enabled = false
So this is set to false as the old frontend has set this to false (locally), always getting the balance as opposed to the balance history. Not sure what you mean by what does this affect in QA (not overwritten in app-config-qa yet on the old service)

From a business logic perspective it seems they wanted to be able to total the balance from every period since the liability date into one figure. Maybe something to clarify with and SME? I'll add a post it for now.

2023-04-04 14:31 UTC, RaminEsfandiari commented on conf/messages.en
> +firstQuarter = January to March
Scaffold prefixes these for each page and we get a lot of duplication of the same content. I'd say we'd only need to separate them with prefixes when we really need to. Also, having content as camel case (where not too long) helps a lot when you want to get a hint of the value represented by that key message in the code and you don't have to jump back to messages files. It's a more descriptive and easier to read pattern IMHO.

The benefit of having them prefixed with page names is that if you want to find all the content of a specific page on the messages file then you can find them much quicker.  

We discussed this with the team before you joined and people seemed happy with this approach but we could have a chat about it again to get your input it on it too. Plus people may have used it and not liked the new pattern so they may be more in favour of the standard prefixed pattern.

2023-04-04 14:31 UTC, RaminEsfandiari commented on conf/messages.en
> +financiallineitem.returncharge = Return <br/><span class="form-hint">for {0} to {1}</span>
Scaffold prefixes these for each page and we get a lot of duplication of the same content. I'd say we'd only need to separate them with prefixes when we really need to. Also, having content as camel case (where not too long) helps a lot when you want to get a hint of the value represented by that key message in the code and you don't have to jump back to messages files. It's a more descriptive and easier to read pattern IMHO.

2023-04-04 14:31 UTC, RaminEsfandiari commented on it/controllers/CheckYourAnswersControllerIntegrationSpec.scala
> +  "CheckYourAnswersController" should {
Created a subtask.

2023-04-05 13:00 UTC, ChrisHillCap approved these changes
Big changes, manually rtested, anything raised would be raised as bug

2023-04-05 13:03 UTC, merged