[DLS-6789] Adding Navigation To Packing Site Details
hmrc/soft-drinks-industry-levy-returns-frontend pull request #89
Opened 2023-04-25 11:11 UTC by JakeReid2020

2023-04-26 14:02 UTC, ChrisHillCap requested changes

2023-04-26 14:02 UTC, ChrisHillCap commented on app/utilitlies/UserTypeCheck.scala
> +def isNewImporter(sdilReturn:SdilReturn,subscription:RetrievedSubscription):Boolean ={
werent we going to put on checking the warehousedetails on the end?

2023-04-26 14:02 UTC, ChrisHillCap commented on app/utilitlies/UserTypeCheck.scala
> +object UserTypeCheck{
```suggestion
object UserTypeCheck {
```

2023-04-26 14:02 UTC, ChrisHillCap commented on app/utilitlies/UserTypeCheck.scala
> +def isNewImporter(sdilReturn:SdilReturn,subscription:RetrievedSubscription):Boolean ={
```suggestion

def isNewImporter(sdilReturn: SdilReturn,subscription: RetrievedSubscription): Boolean = {
```

2023-04-26 14:02 UTC, ChrisHillCap commented on it/controllers/testSupport/ITCoreTestData.scala
> +  def newPackerPartialNewImporterAnswers = emptyUserAnswers
do we need all these values? cant we just have the answers contain the things that are required on the page?
cant we just set the answers that are needed on the page to do the test

2023-04-28 11:43 UTC, JayenKerai approved these changes

2023-04-28 13:06 UTC, ChrisHillCap approved these changes

2023-04-28 13:06 UTC, merged